### ISSUE TITLE
Why google test is needed when cmaking?

### ISSUE THREAD

**Issue by wangshun1121** [voges/calq#1]
As I mentioned, why google test is needed when cmaking?

**Comment by voges** [comment]
Hello Wangshun,

Thanks for opening this issue? What exactly do you mean, i.e., how would you like the build process to work? With GoogleTest being an optional requirements?

Best regards,
Jan

**Comment by wangshun1121** [comment]
What I mean is that: I don't want GoogleTest when cmaking, and I thank it's not that necessary. I have to git clone GoogleTest when complying, which spend much time!

**Comment by wangshun1121** [comment]
By the way, the compressed source codes in Release can't be complied directly by cmake

**Comment by voges** [comment]
Thanks for your prompt replies. Yes, GoogleTest is not necessary for building CALQ. We are currently in the drafting process of a new CALQ release. We well take care of disabling default git cloning of GoogleTest in the next release.

You also mention that you are not able to compile the (latest?) release. Could you point me to which error exactly you encounter?
